server:
  port: 9000

spring:
  application:
    name: roses-spring-boot-admin
  profiles:
    active: @spring.active@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.214:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS