server:
  port: 8102

spring:
  application:
    name: roses-order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_order?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        watch-delay: 1000
        server-addr: 127.0.0.1:8848

ribbon:
  eager-load:
    enabled: true

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:cn/stylefeng/roses/order/modular/mapper/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

roses:
  scanner:
    app-code: roses-order
    app-name: demo-订单服务
    open: false
  message:
    checkInterval: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always